name: build and create docker image for Bank Account Application
on:
  workflow_dispatch:

jobs:
  build-push-dockerhub:
    name: build and push Bank Application
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Individual repos
        uses: actions/checkout@v4
      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Maven build and Test
        run: mvn clean install

      - name: Build & push bank-application-service Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: riturajdocker/bank-application-service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}